spring:
  datasource:
    url: jdbc:mariadb://3.37.87.54:3306/ticketing
    username: "root"
    password: "!123456"
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # create -> create옵션은 서버 끌 때 테이블 다 삭제되니까 none이나 update로 바꿔서 사용하면 됩니다.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  # 선택 (SQL 로그 더 자세히 보고 싶을 때)
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace